#!/usr/bin/python

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright (C) 2011  Benjamin Ooghe  <b.ooghe@free.fr>

import re
from pipetk import PipeTemplate

class CleanUrls(PipeTemplate):
    WITH_ENDL = True

    def process(self, line):
        line = re.sub(r"[\?\&](utm_medium|utm_source|utm_campaign|xtor)=[^\&]*", r"", line, re.IGNORECASE)
        line = re.sub(r"/#!/", r"/", line)
        line = re.sub(r"(http://[^ ]+)#[^# ]*", r"\1", line, re.IGNORECASE)
        yield line

if __name__ == "__main__":
    CleanUrls().run()

# vim:set shiftwidth=4 tabstop=4 expandtab:

