#!/usr/bin/python
# -*- coding:Utf-8 -*-

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright (C) 2011  Laurent Peuch  <cortex@worlddomination.be>

import sys
import re
from urllib2 import urlopen, HTTPError
from pipetk import URLPipeTemplate

class Detinify(URLPipeTemplate):
    def __init__(self, ignore_list=list()):
        self.ignore_list = map(self._format_urls, ignore_list)

    def _format_urls(self, url):
        if url.startswith("http://"):
            url = "https?://" + url[7:]
        elif url.startswith("https://"):
            url = "https?://" + url[8:]
        else:
            url = "https?://" + url
        return url + ".*"

    def process_url(self, url):
        if filter(lambda x: re.match(x, url), self.ignore_list):
            return url
        try:
            return urlopen(url).geturl()
        except HTTPError:
            return url

if __name__ == "__main__":
    Detinify(sys.argv[1:]).run()

# vim:set shiftwidth=4 tabstop=4 expandtab:
