#!/usr/bin/python
# -*- coding:Utf-8 -*-

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright (C) 2011  Laurent Peuch  <cortex@worlddomination.be>

import time
import sys

from pipetk import PipeTemplate

class Lag(PipeTemplate):
    WITH_ENDL = False
    def __init__(self, duration=1):
        self.duration = duration

    def process(self, line):
        yield line
        time.sleep(self.duration)

if __name__ == "__main__":
    Lag(float(sys.argv[1]) if len(sys.argv) > 1 else 1).run()

# vim:set shiftwidth=4 tabstop=4 expandtab:
