#!/usr/bin/python
# -*- coding:Utf-8 -*-

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright (C) 2011  Laurent Peuch  <cortex@worlddomination.be>

import sys
import os

def run():
    try:
        os.mkfifo(sys.argv[1])
    except OSError:
        pass
    pipe = open(sys.argv[1], "r+")
    a = pipe.readline()
    while a:
        sys.stdout.write(a)
        sys.stdout.flush()
        a = pipe.readline()

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print "need name for the namedpipe"
        sys.exit(0)
    run()

# vim:set shiftwidth=4 tabstop=4 expandtab:
