#!/usr/bin/python

import sys

anti_doublons = set()
a = sys.stdin.readline()
while a:
    if a not in anti_doublons:
        sys.stdout.write(a)
        sys.stdout.flush()
        anti_doublons.add(a)
    a = sys.stdin.readline()
