#!/usr/bin/python
# -*- coding:utf-8 -*-

import sys
from urllib2 import urlopen
from BeautifulSoup import BeautifulSoup

def run():
    url = sys.stdin.readline()
    while url:
        try:
            html = urlopen(url).read()
            soup = BeautifulSoup(html)
            title = soup.title.string if soup.title else u''

            url = u'%s %s\n' % (url[:-1], title)
            sys.stdout.write(url.encode('utf-8'))
        except Exception, e:
            sys.stderr.write("%s" % e)
        sys.stdout.flush()
        url = sys.stdin.readline()

if __name__ == "__main__":
    run()

# vim:set shiftwidth=4 tabstop=4 expandtab:
