#!/usr/bin/python
# -*- coding:utf-8 -*-

import sys
from urllib2 import urlopen
from BeautifulSoup import BeautifulSoup

def run():
    a = sys.stdin.readline()
    while a:
        try:
            html = urlopen(url).read()
            title = BeautifulSoup(html).title.string

            a = "%s %s\n" % (a[:-1], title)
            sys.stdout.write(a)
        except Exception, e:
            sys.stderr.write("%s" % e)
        sys.stdout.flush()
        a = sys.stdin.readline()

if __name__ == "__main__":
    run()

# vim:set shiftwidth=4 tabstop=4 expandtab:
